accounts:
  - name: "Account 1"
    username: "account1@example.com"
    password: "env:MAIL_ACCOUNT_1_PASSWORD"
    emailHost: "smtp.example.com"
    emailPort: 587
  - name: "Account 2"
    username: "account2@example.com"
    password: "env:MAIL_ACCOUNT_2_PASSWORD"
    emailHost: "smtp.example.com"
    emailPort: 587

buckets:
  - name: "bucket1"
    path: "bucket1"
    accessKeyId: "env:BUCKET1_ACCESS_KEY_ID"
    secretAccessKey: "env:BUCKET1_SECRET_ACCESS_KEY"
    region: "region"
  - name: "bucket2"
    path: "templates"
    accessKeyId: "env:BUCKET2_ACCESS_KEY_ID"
    secretAccessKey: "env:BUCKET2_SECRET_ACCESS_KEY"
    region: "region"

templates:
  - name: "Template 1"
    subject: "Template 1 Subject"
    filename: "template1.mjml"
    bucketId: "bucket1"
    storageType: "S3"
  - name: "Template 2"
    subject: "Template 2 Subject"
    filename: "template2.mjml"
